package cl.testregla.testregla;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(c332767ff296e6cd8cf51458371bdd1c)
 */
public class Person extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Boolean adult;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer age;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String name;

    public Person() {
    }

    public Person(java.lang.Integer age, java.lang.Boolean adult, java.lang.String name) {
        this.age = age;
        this.adult = adult;
        this.name = name;
    }


    
    public java.lang.Boolean getAdult() {
        return this.adult;
    }

    public void setAdult(java.lang.Boolean adult) {
        this.adult = adult;
    }
    
    public java.lang.Integer getAge() {
        return this.age;
    }

    public void setAge(java.lang.Integer age) {
        this.age = age;
    }
    
    public java.lang.String getName() {
        return this.name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }
}