package cl.testregla.testregla;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(51ae783e050dc95ab9879928234412c4)
 */
public class Person  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Boolean adult;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer age;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Character name;

    public Person() {
    }

    public Person(java.lang.Integer age, java.lang.Character name, java.lang.Boolean adult) {
        this.age = age;
        this.name = name;
        this.adult = adult;
    }


    
    public java.lang.Boolean getAdult() {
        return this.adult;
    }

    public void setAdult(java.lang.Boolean adult) {
        this.adult = adult;
    }
    
    public java.lang.Integer getAge() {
        return this.age;
    }

    public void setAge(java.lang.Integer age) {
        this.age = age;
    }
    
    public java.lang.Character getName() {
        return this.name;
    }

    public void setName(java.lang.Character name) {
        this.name = name;
    }
}